apiVersion: v1
kind: Service
metadata:
  name: cartservicenpservice
spec:
  type: NodePort
  selector:
    app: cartservice
  ports:
    - name: cartsevice
      protocol: TCP
      port: 80
      targetPort: 80