apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservicecontainer
          image: eskill001/cartserviceimagerepository:latest